### ISSUE TITLE
Version published on npm (version 2.2.1) is not pushed in git

### ISSUE THREAD

**Issue by kaasdude** [marcojonker/data-elevator-mongodb#4]
Hey Marco,

I dearly want to update the mongodb npm module in a pull request. Because we dearly want to implement a new kind of mongodb connection uri, which connects to mongodb replica sets with the following signature: `mongodb+srv://`.

I can't seem to find the right commit/tag which corresponds with the latest version on npm (2.2.1).

I hope you've got a moment.

Cheers Ivo :-D

**Comment by marcojonker** [comment]
Thanks for letting me know, cheesedude. Pushed it.
